//------------------------------------------------------------------
// EasyLanguage Code for Tradestation / MultiCharts of Strategy 0.48092
//
//   Generated by StrategyQuant X Build 143
//   at 12/04/2025 08:14
//  
//   Backtested on @GR / M5, 2024.01.01 - 2025.12.03 
//
//   Generated for Main chart = Current Symbol / Current TF;
//------------------------------------------------------------------

inputs:
	// Strategy variables
	MagicNumber(11111),
	EMAPeriod1(20),
	MACDFast1(8),
	MACDSlow1(17),
	MACDSmooth1(9),
	ExitAfterBars1(90),
	ProfitTargetCoef1(15.7),
	StopLossCoef1(1.7),

	// Trading Options
    
	DontTradeOnWeekends(true),
	FridayCloseTime(1545),
	SundayOpenTime(1815),	
	ExitAtEndOfDay(false),
	DayExitTime(2304),    
	ExitOnFriday(false),
	FridayExitTime(2040),
	LimitSignalsTimeRange(false),
	SignalTimeRangeFrom(0800),
	SignalTimeRangeTo(1600),
	ExitAtEndOfRange(false),
	OrderTypeToExit(0),
	LimitMaxDistanceFromMarket(false),  // Limit max order price distance from market
	MaxDistancePct(6),  // Maximum distance from market price in %
	MaxTradesPerDay(0),
	MinimumSL(8),  // Minimum SL in ticks/pips, 0 means unlimited
	MaximumSL(0),  // Maximum SL in ticks/pips, 0 means unlimited
	MinimumPT(8),  // Minimum PT in ticks/pips, 0 means unlimited
	MaximumPT(0),  // Maximum PT in ticks/pips, 0 means unlimited	
	UseInitialStopLoss(false),  // Sets StopLoss immediately after the order gets filled. Otherwise SL is set on next bar.
    // Template for a trading option /TradingOptions/LimitOver_variables.tpl missing, ignoring!


	// Money Management - Fixed size
	mmLots(1.0),
    double mmMultiplier(1.0),
	InitialCapital(150000);

vars:
	// Internal variables
	LongEntrySignal(false),
	ShortEntrySignal(false),
	LongExitSignal(false),
	ShortExitSignal(false),
	NumberOfSharesLong(0),NumberOfSharesShort(0),
	tickSize(MinMove/PriceScale),
	OpenOrdersAllowed(true),
	IntPriceLevel(0),IntPriceLevelLong(0),IntPriceLevelShort(0),IntLongSL(0),IntShortSL(0),IntPT(0),
	IntLongTS(0),IntShortTS(0),
	IntLongBE(0),IntShortBE(0),
	InitDone(false),
	LongSLPlaced(false),ShortSLPlaced(false),
   OrderSize(0),
   RemainingSize(0),
   ATMExitPrice(0);

	Array: bool cond[100](false);
   


// =================================================================
// TRADING OPTIONS LOGIC
// =================================================================
OpenOrdersAllowed = true;

// Dont trade on weekends
if DontTradeOnWeekends then begin
	if DayOfWeek(Date) = 5 then begin
		if FridayCloseTime <> 0000 and Time >= FridayCloseTime then begin
			OpenOrdersAllowed = False;
		end;	
	end
	else if DayOfWeek(Date) = 6 then begin
		OpenOrdersAllowed = False;
	end
	else if DayOfWeek(Date) = 0 and Time < SundayOpenTime then begin
		OpenOrdersAllowed = False;
	end; 
end;

// Exit on close (end of day)
if ExitAtEndOfDay then begin
	if DayExitTime <> 0000 then begin 
		if LimitSignalsTimeRange = False then begin 
		 	if Time >= DayExitTime then begin 
				if (MarketPosition > 0) then Sell("ExitEndOfDayL1") This Bar On Close;
				if (MarketPosition < 0) then BuyToCover("ExitEndOfDayS1") This Bar On Close;
				OpenOrdersAllowed = False;
			end;
		end;
		if LimitSignalsTimeRange = True then begin
			if Time >= DayExitTime and Time < SignalTimeRangeFrom then begin
				if (MarketPosition > 0) then Sell("ExitEndOfDayL2") This Bar On Close;
				if (MarketPosition < 0) then BuyToCover("ExitEndOfDayS2") This Bar On Close; 
				OpenOrdersAllowed = False;
			end;
			if DayExitTime >= SignalTimeRangeFrom and  SignalTimeRangeFrom < SignalTimeRangeTo then begin
				if Time >= DayExitTime and Time >= SignalTimeRangeFrom then begin
					if (MarketPosition > 0) then Sell("ExitEndOfDayL3") This Bar On Close;
					if (MarketPosition < 0) then BuyToCover("ExitEndOfDayS3") This Bar On Close;
					OpenOrdersAllowed = False;
				end;
			end;
		end;
	end
	else SetExitOnClose;
end;


// Exit on Friday
if ExitOnFriday then begin
	if DayOfWeek(Date) = 5 then begin
		if FridayExitTime <> 0000 and Time >= FridayExitTime then begin
			if (MarketPosition > 0) then Sell("ExitFridayL") This Bar On Close;
			if (MarketPosition < 0) then BuyToCover("ExitFridayS") This Bar On Close;
			OpenOrdersAllowed = False;
		end;
	end
	else if DayOfWeek(Date) = 6 then begin
		OpenOrdersAllowed = False;
	end; 
end;

// Limit time range
if(OpenOrdersAllowed = True and LimitSignalsTimeRange = True and ((SignalTimeRangeFrom < SignalTimeRangeTo and (Time < SignalTimeRangeFrom or Time >= SignalTimeRangeTo)) or 
									   (SignalTimeRangeFrom >= SignalTimeRangeTo and (Time < SignalTimeRangeFrom and Time >= SignalTimeRangeTo)))
) then OpenOrdersAllowed = False;


// Exit At End Of Range
if LimitSignalsTimeRange = True and ExitAtEndOfRange = true then begin
	if SignalTimeRangeFrom < SignalTimeRangeTo and Time >= SignalTimeRangeTo then begin
		if (MarketPosition > 0) then Sell("ExitEndOfRangeL1") This Bar On Close;
		if (MarketPosition < 0) then BuyToCover("ExitEndOfRangeS1") This Bar On Close;
	end;
	if SignalTimeRangeFrom >= SignalTimeRangeTo and Time >= SignalTimeRangeTo and Time < SignalTimeRangeFrom then begin
		if (MarketPosition > 0) then Sell("ExitEndOfRangeL2") This Bar On Close;
		if (MarketPosition < 0) then BuyToCover("ExitEndOfRangeS2") This Bar On Close;
	end;
end;


// Max trades per day
if(OpenOrdersAllowed = True and MaxTradesPerDay <> 0 and EntriesToday(Date) >= MaxTradesPerDay) then
	OpenOrdersAllowed = False;
// Template for a trading option /TradingOptions/LimitOver_code.tpl missing, ignoring!
    
    

// =================================================================
// TRADING RULES LOGIC
// =================================================================
               
//------------------------------------------------------------------
// Rule: Trading signals
//------------------------------------------------------------------
Value1= SQ_MACD(Close, MACDFast1, MACDSlow1, MACDSmooth1, 0)[1+1];
Value2= SQ_MACD(Close, MACDFast1, MACDSlow1, MACDSmooth1, 0)[1];
LongEntrySignal = (((SQ_IsFalling(SQ_EMA(Close, EMAPeriod1)[1], 3, true)[1] = 1) and ((Value1 < -0.8) and (Value2 > -0.8))) and (Value2 < 0.5));


ShortEntrySignal = false;


LongExitSignal = false;


ShortExitSignal = false;




                
//------------------------------------------------------------------
// Rule: Long entry
//------------------------------------------------------------------
if LongEntrySignal

then begin
	// Action #1
	if(OpenOrdersAllowed) then begin
				NumberOfSharesLong = mmLots * mmMultiplier;
		If NumberOfSharesLong > 0 Then begin
			if(MarketPosition = 0) then begin
				Buy NumberOfSharesLong shares next bar at market;

				If UseInitialStopLoss Then begin
                  IntLongSL = SQ_ConvertToPips(Absvalue(Round2Fraction( - (StopLossCoef1 * SQ_ATR_R(20, 1)))));
                  If MinimumSL > 0 and IntLongSL < MinimumSL Then IntLongSL = MinimumSL;
                  If MaximumSL > 0 and IntLongSL > MaximumSL Then IntLongSL = MaximumSL;

                  If IntLongSL > 0 Then begin
                     SetStopContract;
                     SetStopLoss((MinMove / PriceScale) * BigPointValue * IntLongSL);
                  end;
                  IntPT = SQ_ConvertToPips(Absvalue(Round2Fraction( + (ProfitTargetCoef1 * SQ_ATR_R(20, 1)))));
                  If MinimumPT > 0 and IntPT < MinimumPT Then IntPT = MinimumPT;
                  If MaximumPT > 0 and IntPT > MaximumPT Then IntPT = MaximumPT;

                  If IntPT > 0 Then begin
                     SetStopContract;
                     SetProfitTarget((MinMove / PriceScale) * BigPointValue * IntPT);
                  end;
				end;
			end;
		end;
	end;
end;

//------------------------
// Orders Exits (SL, PT, Trailing) for Rule: Long entry 
//------------------------
if(MarketPosition > 0) then begin

	LongSLPlaced = false;

	If BarsSinceEntry(0) = 0 then begin
		IntLongSL = 0;
		IntLongTS = 0;
		IntLongBE = 0;
	end;

	// StopLoss
	IntLongSL = Round2Fraction(EntryPrice - (StopLossCoef1 * SQ_ATR_R(20, 1)));
	IntLongSL = SQ_CorrectMinMaxSLPT(IntLongSL, MinimumSL, MaximumSL, true);
	If IntLongSL <> 0 Then begin
		Sell("LongSL") next bar at IntLongSL stop;
		LongSLPlaced = true;
	end Else IntLongSL = 0;

	// ProfitTarget init
	IntPT = Round2Fraction(EntryPrice + (ProfitTargetCoef1 * SQ_ATR_R(20, 1)));
	IntPT = SQ_CorrectMinMaxSLPT(IntPT, MinimumPT, MaximumPT, false);
	If IntPT < 0 Then IntPT = 0;
	
	// ExitAfterBars
	if (ExitAfterBars1 > 0 and BarsSinceEntry(0) >= ExitAfterBars1) then
		Sell("LongExitAfterXBars") next bar at market;
		
	If IntPT <> 0 then begin 
		Sell next bar at IntPT limit;
	end;
		
	if LongSLPlaced = false and IntLongSL > 0 then begin
		// no SL activated this bar, use default one - handling if there is no SL, only Trailing stop or Move2BE
		Sell next bar at IntLongSL stop;
	end;	
end;

                
//------------------------------------------------------------------
// Rule: Short entry
//------------------------------------------------------------------
if (ShortEntrySignal and (LongEntrySignal = false))

then begin
end;


                
//------------------------------------------------------------------
// Rule: Long exit
//------------------------------------------------------------------
if ((LongExitSignal and (LongEntrySignal = false)) and (MarketPosition > 0))

then begin
	// Action #1
Sell("ClosePositionLong") next bar at market;
end;


                
//------------------------------------------------------------------
// Rule: Short exit
//------------------------------------------------------------------
if ((ShortExitSignal and (ShortEntrySignal = false)) and (MarketPosition < 0))

then begin
	// Action #1
BuyToCover("ClosePositionShort") next bar at market;
end;


                



